name: crispy

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy>=1.19.0
  - scipy>=1.5.0
  - matplotlib>=3.3.0
  - astropy>=4.0
  - photutils>=1.0.0
  - sphinx>=4.0
  - sphinx_rtd_theme
  - nbsphinx
  - pip