name: crispy
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.19.0
  - scipy>=1.5.0
  - matplotlib>=3.3.0
  - astropy>=4.0
  - photutils>=1.0.0
  - jupyter
  - notebook
  - ipython
  - pandas
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - pip
  # Additional development tools
  - git
  # Testing framework
  - pytest>=7.0
  - pytest-cov
  - pytest-xdist
  - pytest-mock
  - pip:
    - pytest-emoji
    - pytest-sugar